# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    container_name: mysql_db
    command: --authentication_policy=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: test_node
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - /Volumes/Seagate/projects/teste-nodejs/db_init.sql:/db_init.sql
